spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/create?seUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES